BUILDROOT_DIR = buildroot
DEFCONFIG_NAME = orangepi_3_defconfig
DEFCONFIG_FILE_SRC = $(DEFCONFIG_NAME)
DEFCONFIG_FILE_DST = $(BUILDROOT_DIR)/configs/$(DEFCONFIG_NAME)
BOARD_DIR_NAME = orangepi-3 
BOARD_DIR_SRC = $(BOARD_DIR_NAME)
BOARD_DIR_DST = $(BUILDROOT_DIR)/board/orangepi/orangepi-3
INITTAB_FILE_SRC = $(BOARD_DIR_NAME)/inittab
INITTAB_FILE_DST = $(BOARD_DIR_DST)/rootfs_overlay/etc/inittab
FIRMWARE_DIR_SRC = firmware
FIRMWARE_DIR_DST = $(BOARD_DIR_DST)/rootfs_overlay/lib/firmware/brcm
FIRMWARE_AG_NAME = fw_bcm43456c5_ag.bin
FIRMWARE_AG_SRC = $(FIRMWARE_DIR_SRC)/$(FIRMWARE_AG_NAME)
FIRMWARE_AG_DST = $(FIRMWARE_DIR_DST)/$(FIRMWARE_AG_NAME)
FIRMWARE_BRCM_NAMES = \
	BCM4345C5.hcd \
	brcmfmac43456-sdio.bin \
	brcmfmac43456-sdio.txt
FIRMWARE_BRCM_DSTS = $(patsubst %,$(FIRMWARE_DIR_DST)/%,$(FIRMWARE_BRCM_NAMES))

all: $(DEFCONFIG_FILE_DST) $(BOARD_DIR_DST) $(FIRMWARE_AG_DST) $(FIRMWARE_BRCM_DSTS)
	make -C $(BUILDROOT_DIR) $(DEFCONFIG_NAME)
	make -C $(BUILDROOT_DIR)

$(DEFCONFIG_FILE_DST): $(DEFCONFIG_FILE_SRC)
	cp $(DEFCONFIG_FILE_SRC) $(DEFCONFIG_FILE_DST)

$(BOARD_DIR_DST): $(BOARD_DIR_SRC)
	cp -R $(BOARD_DIR_SRC) $(BOARD_DIR_DST)

$(FIRMWARE_AG_DST): $(BOARD_DIR_DST)
	mkdir -p $(FIRMWARE_DIR_DST)
	cp $(FIRMWARE_AG_SRC) $(FIRMWARE_AG_DST)

$(FIRMWARE_DIR_DST)/%: $(FIRMWARE_DIR_SRC)/brcm/%
	cp $< $@

clean:
	rm -f $(DEFCONFIG_FILE_DST)
	rm -rf $(BOARD_DIR_DST)

.PHONY: all clean
